Update programs
Update programs to a common interface. Error checks inserted in all
programs and xbase. Introduced a set of program-groups that provide
similar functionality, e.g. the variable `sed_like_programs'.

xbody:  Now replaces xdriver
xawk:   Now replaces xawk2
xcount: Now replaces xcountx, as it can handle multiple-count fields.
xsort:  Completely rewritten (formerly xdriver)
xcut:   Completely rewritten (fomrerly xdriver)

diff --git a/xbase b/xbase
--- a/xbase
+++ b/xbase
@@ -1,50 +1,141 @@
-#!/bin/sh
+#!/bin/bash
 
-export enable_stack_trace="yes"
+# Author:   Ronny Biemann
+#           Copyright 2016
+# File:     xbase
+# License:  GPL-3.0
+
+# Dependencies:
+# bash (required)
+# coreutils (required)
+# grep (required)
+# sed (required)
+# util-linux  (optional)
+
+export enable_call_stack=yes
+export enable_warning_location=yes
+declare -r default_field_separator=,
+
+# Register process ID of top-level shell. This is required to allow the
+# die-function to globally abort the current program. Otherwise only the
+# sub-shell would be terminated.
+# Source: http://stackoverflow.com/a/9894126
+declare -r top_level_pid=$$
 
 # Default commands
-_awk="/usr/bin/mawk"
+declare -ar awk_like_programs=("mawk" "awk")
+declare -ar cut_like_programs=("cut")
+declare -ar egrep_like_programs=("egrep")
+declare -ar fgrep_like_programs=("fgrep")
+declare -ar getopt_like_programs=("getopt")
+declare -ar join_like_programs=("join")
+declare -ar nl_like_programs=("nl")
+declare -ar parallel_like_programs=("parallel")
+declare -ar sed_like_programs=("sed")
+declare -ar split_like_programs=("split")
+declare -ar sort_like_programs=("sort")
 _cut="/usr/bin/cut -d%fs"
 _echo="/bin/echo"
-_join="/usr/bin/join -t%fs"
 _nl="/usr/bin/nl -s%fs"
-_sed="/bin/sed"
 _shuf="/usr/bin/shuf"
-_sort="/usr/bin/sort --buffer-size=3G"
+_sort="/usr/bin/sort ${SFLAGS:---buffer-size=3G}"
 
+# Write MESSAGE to stderr
+#
+# Usage: warning MESSAGE...
 function warning()
 {
-  echo "Warning: $@" >&2
+  #{{{
+  case "${enable_warning_location:-no}" in
+  yes)
+    declare -r location="$(caller 0 | awk '{print $3":"$1;}'): "
+    ;;
+  *)
+    declare -r location=""
+    ;;
+  esac
+
+  echo "${location}Warning: $@" >&2
+  #}}}
 }
 
+# Abort execution with error CODE after printing an error MESSAGE to stderr and
+# the content of the call-stack(optionally). The output of the call-stack can
+# be enabled by setting `enable_call_stack' to `yes'. This will only be
+# ignored, if the column-program from util-linux package isn't installed.
+# 
+# Usage: die CODE MESSAGE...
 function die()
 {
-  return_code=$1
+  #{{{
+  return_code=${1:?Missing CODE}
   shift
 
-  if [ x"yes" = x${enable_stack_trace:-no} ]; then
-    local frame=0
+  # Suppress printing call-stack, if column program (linux-utils) isn't found
+  if [ "yes" = "${enable_call_stack:-no}" ] && [ -x "$(which column)" ]; then
     echo "Call stack:" >&2
-    while caller $frame; do
-      # Read next frame
-      frame=$((frame + 1));
-    done >&2
+
+    # Print all frame on call-stack to stderr
+    local frame=0
+    while caller $frame; do ((frame += 1)); done \
+      | (printf "frame\tline\tfunction\tfile\n"; nl) \
+      | column --table \
+      | sed -e 's/^/  /' >&2
   fi
 
   echo "Error: $@" >&2
+
+  # Source: http://stackoverflow.com/a/9894126
+  kill -s TERM ${top_level_pid}
   exit $return_code
+  #}}}
 }
 
+# Usage: set_fsep [FS]
 function set_fsep()
 {
-  # Read (optional) field-separator
-  # Default is comma
-  declare -r fsep=${1:-,}
-  shift
+  #{{{
+  declare -r fsep=${1:-${default_field_separator}}
+  grep '@' <<< "${fsep}" && die -1 "Field separator must not contain \`@'!"
+  echo "${fsep}"
+  #}}}
+}
 
-  grep '@' <<< "$fsep" && die -1 "Field separator must not contain \`@'!"
+# Generate a common help message for configuring the field separator from input
+# ARG. This is generally done by the flag `-t ARG'
+#
+# Usage: fsep_help_message [ARG]
+function fsep_help_message()
+{
+  echo "Use ${1:-FS} instead of COMMA for field delimiter"
+}
 
-  echo $fsep
+# Generate a common help message for the flags to request help. Generally these
+# are -h or --help.
+#
+# Usage: help_help_message
+function help_help_message()
+{
+  echo "Print this message and terminate"
+}
+
+# Usage: getopt_help_message PROGRAM BACKEND VARIABLE [DEFAULT_FLAGS]
+function getopt_help_message()
+{
+  local -r program=${1:?Missing PROGRAM}
+  local -r backend=${2:?Missing BACKEND}
+  local -r variable=${3:?Missing VARIABLE}
+  local -r getopt=$(find_program_like ${getopt_like_programs})
+
+  cat << EOF
+As ${program} is a frontend to ${backend}, two methods
+are implemented to pass extra options to the underlying backend:
+1.  ${getopt} is used to parse commandline options. It stops parsing options on
+    \`--' and takes all input thereafter as non-option arguments. These
+    non-option arguments are passed directly to the backend
+2.  By defining the environment variable \`${variable}' options can be passed
+    to the backend (default is \`${4}').
+EOF
 }
 
 function replace_fsep()
@@ -60,66 +151,74 @@ function replace_fsep()
   # Read (optional) pattern for field-separator
   # Default pattern is `%fs'
   declare -r var=${1:-%fs}
-  shift
 
   sed "s@$var@$sep@g" <<< "$cmd"
 }
 
+# Join elements of ARRAY into a single line. Subsequent elements will be
+# separated by FS.
+#
+# Usage: join_by ARRAY [FS]
 function join_by()
 {
+  #{{{
   # Read header names as first argument
   declare -ra x=("${!1:?Missing array}")
-  shift
 
   # Read (optional) field-separator
   # Default field-separator is comma `,'
-  local IFS=${1:-,}
-  shift
-
+  local IFS=${2:-,}
   echo "${x[*]}"
+  #}}}
 }
 
+# Parse column names from STR. Therefore STR must be a single line and it is
+# split on FS and the column names are saved in the array <PREFIX>fields. PREFIX
+# is an optional argument and default to an empty string.
+#
+# Usage: parse_header STR FS [PREFIX]
 function parse_header()
 {
-  # Line containing header
-  declare -r header=${1:?Missing header}
-  shift
-
-  declare -r fsep=${1:?Missing field separator}
-  shift
-
-  # Variable name prefix
-  declare -r prefix=${1:-""}
-  shift
-
-  local IFS="$fsep"
+  #{{{
   declare -a fields
-  declare -a columns
+  # declare -a columns
 
-  read -r -a columns <<< "$header"
+  local IFS=${2:?Missing FS}
+  read -r -a fields <<< "${1:?Missing STR}"
 
-  for fn in "${columns[@]}"; do
-    # Save current field name and options
-    declare -i cnt=$((${#fields[@]} + 1))
-    fields[$cnt]=${fn:?Empty field name}
+  # Check for non-empty column names
+  declare -i no=1
+  for fn in "${fields[@]}"; do
+    [ -z "${fn}" ] && die -1 "Field name ${no} must not be empty!"
+    ((no + 1))
   done
 
   # Export arrays with prefix as global variables
-  eval "$prefix""fields"='("${fields[@]}")'
+  eval "${3}fields"='("${fields[@]}")'
+  #}}}
 }
 
-function find_fields()
+# Locate fields within ARRAY by their column name. A field specifier may
+# additionally contain sort(1) flags. These flags are appended to the column
+# name, thus FIELD is `NAME[:FLAGS]'. According to the manpage of sort(1),
+# amongst others FLAGS may contain `g' for sorting by generic numbers. The
+# function will define the arrays <PREFIX>index, <PREFIX>flags and
+# <PREFIX>found. The first two arrays store the column number and sort flags of
+# the FIELDs by their order passed to the function. The third array contains
+# the column names of the FIELDs sorted by their column number. The function
+# will fail with an error message if at least one FIELD could not be found in
+# the header.
+#
+# Usage: locate_fields ARRAY PREFIX FIELD...
+function locate_fields()
 {
-  # Read header names as first argument
-  declare -ra header=(${!1:?Missing header})
-  shift
-
-  # Read prefix
-  declare -r prefix=${1?Missing prefix}
-  shift
+  #{{{
+  # Read header names and prefix
+  declare -ra header=(${!1:?Missing ARRAY})
+  declare -r prefix=${2:?Missing PREFIX}
+  shift 2
 
   declare -a index
-  declare -a found
   declare -a flags
 
   for fn in "$@"; do
@@ -127,16 +226,17 @@ function find_fields()
     declare -i fn_idx=-1
     declare -i hn_idx=0
 
-    # Check for non-empty field name
-    _N=${fn:?Empty field name}
-    _N=${_N%%:*}
+    # Strip sort flags from field name
+    [ -z "${fn}" ] && die -1 "Empty field name!"
+    _N=${fn%%:*}
 
     # Keep suffix from field name, i.e. from next character on after `:'
     _O=${fn:$((${#_N} + 1))}
 
+    # Search for _N in column names
     for hn in "${header[@]}"; do
-      if [ "$hn" = "$_N" ]; then
-        fn_idx=$hn_idx
+      if [ "${hn}" = "${_N}" ]; then
+        fn_idx=${hn_idx}
         break
       fi
 
@@ -144,149 +244,103 @@ function find_fields()
     done
 
     # Raise error, if field could not be found
-    [ -1 -eq $fn_idx ] && die -1 "No such field: $fn"
+    [ -1 -eq ${fn_idx} ] && die -1 "No such field: ${_N}"
 
-    declare -i cnt=${#index[@]}
-    index[$cnt]=$fn_idx
-    flags[$cnt]=$_O
+    index+=("${fn_idx}")
+    flags+=("${_O}")
   done
 
   # Sort selected fields by column-number
   declare -i idx
   declare -ra sorted_index=($(printf "%s\n" "${index[@]}" | sort -n))
 
-  for idx in "${sorted_index[@]}"; do
-    declare -i cnt=${#found[@]}
-    found[$cnt]=${header[$idx]}
-  done
+  declare -a found
+  for idx in "${sorted_index[@]}"; do found+=("${header[${idx}]}"); done
 
   # Export arrays with prefix as global variables
-  eval "$prefix""index"='("${index[@]}")'
-  eval "$prefix""found"='("${found[@]}")'
-  eval "$prefix""flags"='("${flags[@]}")'
+  eval "${prefix}index"='("${index[@]}")'
+  eval "${prefix}found"='("${found[@]}")'
+  eval "${prefix}flags"='("${flags[@]}")'
+  #}}}
 }
 
+# This function returns the arrays <PREFIX>index, <PREFIX>flags and
+# <PREFIX>found for all available fields. This has the same effect as it would,
+# when passing all available fields to the locate_fields-function. The sort(1)
+# FLAGS are applied to all fields (default is `g').
+#
+# Usage: select_all_fields ARRAY PREFIX [FLAGS]
 function select_all_fields()
 {
-  # Read header names as first argument
-  declare -ra header=(${!1:?Missing header})
-  shift
-
-  # Read prefix
-  declare -r prefix=${1?Missing prefix}
-  shift
+  #{{{
+  declare -ra header=(${!1:?Missing ARRAY})
+  declare -r prefix=${2?Missing PREFIX}
 
   declare -a index
-  declare -a found
   declare -a flags
+  declare -a found
 
   for fn in "${header[@]}"; do
-
-    declare -i fn_idx=-1
-    declare -i hn_idx=0
-
-    # Check for non-empty field name
-    _N=${fn:?Empty field name}
-    _N=${_N%%:*}
-
-    # Keep suffix from field name, i.e. from next character on after `:'
-    _O=${fn:$((${#_N} + 1))}
-
-    for hn in "${header[@]}"; do
-      if [ "$hn" = "$_N" ]; then
-        fn_idx=$hn_idx
-        break
-      fi
-
-      hn_idx=$((hn_idx + 1))
-    done
-
-    # Raise error, if field could not be found
-    [ -1 -eq $fn_idx ] && die -1 "No such field: $fn"
-
-    declare -i cnt=${#index[@]}
-    index[$cnt]=$fn_idx
-    flags[$cnt]=$_O
-  done
-
-  # Sort selected fields by column-number
-  declare -i idx
-  declare -ra sorted_index=($(printf "%s\n" "${index[@]}" | sort -n))
-
-  for idx in "${sorted_index[@]}"; do
-    declare -i cnt=${#found[@]}
-    found[$cnt]=${header[$idx]}
+    index+=("${#index[@]}")
+    flags+=("${3:-g}")
+    found+=("${fn}")
   done
 
   # Export arrays with prefix as global variables
-  eval "$prefix""index"='("${index[@]}")'
-  eval "$prefix""found"='("${found[@]}")'
-  eval "$prefix""flags"='("${flags[@]}")'
+  eval "${prefix}index"='("${index[@]}")'
+  eval "${prefix}found"='("${found[@]}")'
+  eval "${prefix}flags"='("${flags[@]}")'
+  #}}}
 }
 
+# Prepend STR to all elements of ARRAY. The result will be stored in
+# <PREFIX>fields. PREFIX is an optional argument and defaults to an empty
+# string.
+#
+# Usage: add_prefix_to_fields ARRAY STR [PREFIX] 
 function add_prefix_to_fields()
 {
-  # Read header names as first argument
-  declare -ra header=(${!1:?Missing header})
-  shift
-
-  # Read prefix as second argument
-  declare -r prefix=(${1:?Missing prefix})
-  shift
-
-  # Read variable-prefix as third argument
-  declare -r var_prefix=(${1:?Missing prefix for variable name})
-  shift
+  #{{{
+  declare -ra header=(${!1:?Missing ARRAY})
+  declare -r str=${2:?Missing STR}
 
   declare -a fields
-
-  for fn in ${header[@]}; do
-    cnt=${#fields[@]}
-    fields[$cnt]="$prefix""$fn"
-  done
+  for fn in ${header[@]}; do fields+=("${str}${fn}"); done
 
   # Export arrays with prefix as global variables
-  eval "$var_prefix""fields"='("${fields[@]}")'
+  eval "${3}fields"='("${fields[@]}")'
+  #}}}
 }
 
+# Append STR to all elements of ARRAY. The result will be stored in
+# <PREFIX>fields. PREFIX is an optional argument and defaults to an empty
+# string.
+#
+# Usage: add_suffix_to_fields ARRAY STR [PREFIX] 
 function add_suffix_to_fields()
 {
-  # Read header names as first argument
-  declare -ra header=(${!1:?Missing header})
-  shift
-
-  # Read suffix as second argument
-  declare -r suffix=(${1:?Missing suffix})
-  shift
-
-  # Read variable-prefix as third argument
-  declare -r var_prefix=(${1:?Missing prefix for variable name})
-  shift
+  #{{{
+  declare -ra header=(${!1:?Missing ARRAY})
+  declare -r str=${2:?Missing STR}
 
   declare -a fields
-
-  for fn in ${header[@]}; do
-    cnt=${#fields[@]}
-    fields[$cnt]="$fn""$suffix"
-  done
+  for fn in ${header[@]}; do fields+=("${fn}${str}"); done
 
   # Export arrays with prefix as global variables
-  eval "$var_prefix""fields"='("${fields[@]}")'
+  eval "${3}fields"='("${fields[@]}")'
+  #}}}
 }
 
+# Delete elements pointed to by INDEX from ARRAY. The result will be stored in
+# <PREFIX>fields. PREFIX is an optional argument and defaults to an empty
+# string.
+#
+# Usage: delete_fields_by_index FIELD INDEX [PREFIX]
 function delete_fields_by_index()
 {
-  # Read header names as first argument
-  declare -ra header=(${!1:?Missing header})
-  shift
-
-  # Read header names as first argument
-  declare -ra select=(${!1:?Missing selection})
-  shift
-
-  # Read variable-prefix as third argument
-  declare -r var_prefix=(${1:?Missing prefix for variable name})
-  shift
+  #{{{
+  declare -ra header=(${!1:?Missing ARRAY})
+  declare -ra select=(${!2:?Missing INDEX})
 
   declare -a fields
   declare -i idx=0
@@ -295,20 +349,44 @@ function delete_fields_by_index()
     declare -i found=0
 
     for jdx in ${select[@]}; do
-      if [ $idx -eq $jdx ]; then
+      if [ ${idx} -eq ${jdx} ]; then
         found=1
         break
       fi
     done
 
     # Only keep column, that wasn't found in selection
-    [ 0 -eq $found ] && fields[${#fields[@]}]=$fn
+    [ 0 -eq ${found} ] && fields+=("${fn}")
 
-    idx=$((idx + 1))
+    ((idx += 1))
   done
 
   # Export arrays with prefix as global variables
-  eval "$var_prefix""fields"='("${fields[@]}")'
+  eval "${3}fields"='("${fields[@]}")'
+  #}}}
+}
+
+# Find any program from the given LIST. The idea is to specify a list of
+# similar programs and allow any of them to fullfill the requirement. The
+# function will return the path to the first element that is found by the order
+# of the LIST. If no program is found, the function will die with an error
+# message.
+#
+# Usage: find_program_like LIST...
+function find_program_like()
+{
+  #{{{
+  for pn in "$@"; do
+    path=$(which ${pn} 2> /dev/null)
+
+    if [ -x "${path}" ]; then
+      echo "${path}"
+      return
+    fi
+  done
+
+  die -1 "Could not find any of: $@"
+  #}}}
 }
 
 # function merge_fields()
diff --git a/xcat b/xcat
--- a/xcat
+++ b/xcat
@@ -1,51 +1,113 @@
-#!/bin/sh
+#!/bin/bash
 
+# Author:   Ronny Biemann
+#           Copyright 2016
+# File:     xcat
+# License:  GPL-3.0
+
+set -e
 source xbase
 
-_cat=$(which cat 2> /dev/null | head -n1)
-_gzip=$(which pigz gzip 2> /dev/null | head -n1)
-_bzip=$(which bzip2 2> /dev/null | head -n1)
-_xz=$(which xz 2> /dev/null | head -n1)
-_lzma=$(which lzma 2> /dev/null | head -n1)
+declare -r program_name=${0##*/}
 
-pos=0
+# Configure filetype-driver
+declare -r _gzip=$(find_program_like pigz gzip)
+declare -r _bzip=$(find_program_like bzip2)
+declare -r _xz=$(find_program_like xz)
+declare -r _lzma=$(find_program_like lzma)
+
+declare -a available_drivers=("plain")
+[ -x "${_bzip}" ] && available_drivers+=("bzip2")
+[ -x "${_gzip}" ] && available_drivers+=("gzip")
+[ -x "${_lzma}" ] && available_drivers+=("lzma")
+[ -x "${_xz}" ] && available_drivers+=("xz")
+
+# Parse command line arguments and feed parsed arguments
+declare -r args=$(getopt --options=h --longoptions=help,driver --name="${program_name}" -- "$@")
+eval set -- "${args}"
+
+# Parse arguments
+while true; do
+  case ${1} in
+  --driver) # Print installed drivers
+    echo "plain --> $(which cat)"
+    [ -x "${_bzip}" ] && echo "bzip --> ${_bzip}"
+    [ -x "${_gzip}" ] && echo "gzip --> ${_gzip}"
+    [ -x "${_lzma}" ] && echo "lzma --> ${_lzma}"
+    [ -x "${_xz}" ] && echo "xz --> ${_xz}"
+    shift
+    exit 0
+    ;;
+
+  -h|--help)  # Print help message
+    cat << EOF
+Usage: ${program_name} [OPT] FILE...
+
+Concatenate FILE contents to standard output. This works like cat(1), except
+that ${program_name} automatically detects filetypes by their filename
+extension and applies an appropriate decompression driver. Driver-specific
+options may be passed through environment variables like XCAT_<DRIVER_FLAGS.
+E.g for plain files (typically the driver is cat(1)):
+  XCAT_PLAIN_FLAGS=--number ${program_name} FILE
+
+Available flags for OPT:
+  --driver
+    List installed drivers
+
+  -h, --help
+    $(help_help_message)
+EOF
+    shift
+    exit 0
+    ;;
+
+  --)
+    shift
+    break
+    ;;
+  esac
+done
+
+declare -i pos=0
 for file in "$@"; do
-  pos=$((pos + 1))
+  ((pos += 1))
 
   # Check if filename is valid
-  [ -z "$file" ] && die -1 "Invalid filename at position $pos!"
+  [ -z "${file}" ] && die -1 "Invalid filename at position ${pos}!"
 
   # Check if file exists (except `-' for stdin)
-  [ ! "-" = "$file" ] && [ ! -e "$file" ] && die -1 "No such file: $file"
+  [ ! "-" = "${file}" ] && [ ! -e "${file}" ] && die -1 "No such file: ${file}"
 
   # Extract fileextension (lower-case)
   filetype=$(tr '[[:upper:]]' '[[:lower:]]' <<< ${file##*.})
 
   # Filetype specific behaviour
   case "$filetype" in
-    gz)
-      [ ! -x "$_gzip" ] && die -1 "No driver for $filetype files!"
-      $_gzip -cd "$file"
-      ;;
+  gz|gzip)
+    [ ! -x "${_gzip}" ] && die -1 "No driver for ${filetype} files!"
+    ${_gzip} -cd ${XCAT_GZIP_FLAGS} "${file}"
+    ;;
 
-    bz2)
-      [ ! -x "$_bzip" ] && die -1 "No driver for $filetype files!"
-      $_bzip2 -cd "$file"
-      ;;
+  bz2|bzip2)
+    [ ! -x "${_bzip}" ] && die -1 "No driver for ${filetype} files!"
+    ${_bzip} -cd ${XCAT_BZIP_FLAGS} "${file}"
+    ;;
 
-    xz)
-      [ ! -x "$_xz" ] && die -1 "No driver for $filetype files!"
-      $_xz -cd "$file"
-      ;;
+  xz)
+    [ ! -x "${_xz}" ] && die -1 "No driver for ${filetype} files!"
+    ${_xz} -cd ${XCAT_XZ_FLAGS} "${file}"
+    ;;
 
-    lzma)
-      [ ! -x "$_lzma" ] && die -1 "No driver for $filetype files!"
-      $_lzma -cd "$file"
-      ;;
+  lzma)
+    [ ! -x "${_lzma}" ] && die -1 "No driver for ${filetype} files!"
+    ${_lzma} -cd ${XCAT_LZMA_FLAGS} "${file}"
+    ;;
 
-    *)
-      [ ! -x "$_cat" ] && die -1 "No driver for $filetype files!"
-      $_cat "$file"
-      ;;
+  *)
+    cat ${XCAT_PLAIN_FLAGS} "${file}"
+    ;;
   esac
 done
+
+# Report success to shell
+exit 0
diff --git a/xdigit b/xdigit
--- a/xdigit
+++ b/xdigit
@@ -1,143 +1,201 @@
-#!/bin/sh
+#!/bin/bash
+
+# Author:   Ronny Biemann
+#           Copyright 2016
+# File:     xdigit
+# License:  GPL-3.0
+
+function clean_up()
+{
+  #{{{
+  for file in "${temporary_files[@]}"; do rm -f "${file}" 2> /dev/null; done
+  #}}}
+}
+
+# Usage: generateDigitizeProgram FIELD BINS [UPPER]
+function generateDigitizeProgram()
+{
+  #{{{
+  local -r _field=${1:?Missing FIELD}
+  local -r _bins=${2:?Missing BINS}
+
+  # How should the boundaries be handled?
+  # upper=no  --> lo <= x <  hi (default
+  # upper=yes --> lo <  x <= hi
+  case "${3:-no}" in
+  yes) local -ra _compare=("<" "<=") ;;
+  *) local -ra _compare=("<=" "<") ;;
+  esac
+
+  cat << EOF
+1 == NR {
+  lower = %%${_bins}%%;
+  print "(%${_field}% ${_compare[0]} lower) { print \$0, 0; next }";
+  class = 1;
+}
+
+1 < NR {
+  upper = %%${_bins}%%;
+
+  print "("lower" ${_compare[0]} %${_field}%) && (%${_field}% ${_compare[1]} "upper") { print \$0, "class"; next}";
+
+  lower = upper;
+  class += 1;
+}
+
+END {
+  print "("upper" ${_compare[1]} %${_field}%) { print \$0, "class"; next }";
+}
+EOF
+  #}}}
+}
+
+set -e
+trap clean_up 0 # EXIT-signal
 
 source xbase
+
+declare -r program_name=${0##*/}
+declare -r getopt_backend=$(find_program_like ${getopt_like_programs[@]})
+declare -r default_xdigit_field=value
+declare -r default_xdigit_class=class
+declare -r default_xdigit_bins=bins
+declare -r default_xdigit_meta_flags=
+declare -r default_xdigit_flags=
+declare -a temporary_files
 
 # Initialize default field-separator
 fsep=$(set_fsep)
 
 # Parse command line arguments and feed parsed arguments
-args=$(getopt -o b:c:f:ht:u -l help -n ${0##*/} -- "$@")
-eval set -- "$args"
+declare -r args=$(${getopt_backend} --options=b:f:ht: \
+  --longoptions=help,bins:,with-class:,upper \
+  --name="${program_name}" -- "$@")
+eval set -- "${args}"
 
-default_class="class"
-default_input="value"
-default_bin="value"
-
+# Parse arguments
 while true; do
-  case $1 in
-    -b)
-      # Read binning limits from this column
-      bin_field=${2:?Invalid bin field}
-      shift 2
-      ;;
+  case ${1} in
+  -b|--bins) # Read binning limits from this column
+    user_bins=${2}
+    shift 2
+    ;;
 
-    -c)
-      # Write class labels into this column
-      class_field=${2:?Invalid class field}
-      shift 2
-      ;;
+  -f) # Read input data from this column
+    user_field=${2}
+    shift 2
+    ;;
 
-    -f)
-      # Read input data from this column
-      input_field=${2:?Invalid input field}
-      shift 2
-      ;;
+  -t) # Field separator
+    fsep=$(set_fsep $2)
+    shift 2
+    ;;
 
-    -t)
-      # Change field sepearator (default is comma)
-      fsep=$(set_fsep $2)
-      shift 2
-      ;;
+  --with-class) # Write class labels into this column
+    user_class=${2}
+    shift 2
+    ;;
 
-    -u)
-      # Allow equality for upper bound
-      operator_lower="<"
-      operator_upper="<="
-      shift
-      ;;
+  --upper)
+    # Allow equality for upper bound
+    user_upper=yes
+    shift
+    ;;
 
-    -h|--help)
-      cat << EOF
-Usage: xdigit [OPT] DATA BINS
-  -b BIN    Use column BIN of BINS-file as binning limits (default: $default_bin)
-  -c CLS    Write class labels into column CLS (default: $default_class)
-  -f INP    Calculate class labels for column INP of DATA-file (default: $default_input)
-  -t FS     Use FS as field separator
-  -u        Change class limits to \`lo < x <= hi'
-  -h|--help Print this message and terminate
+  -h|--help)
+    cat << EOF
+Usage: xdigit [OPT] DATA BINS [-- ...]
 
-Class limits (BINS)
-  By default are limited by a lower bound (inclusive) and an upper bound
-  (exclusive). This behaviour can be change by the -u flag. Valid classes
-  are numbered from 1 to N, where N is the number of class limits. There
-  are two implicit classes, that contain all elements
-    0:    less than the lowest lower bound
-    N+1:  greater than the highest upper bound.
+Calculate class labels for input DATA. The class limits are taken from the
+BINS-file. Both DATA and BINS might be compressed files, as they are passed to
+xcat, which can transparently decompress the data based on the filename
+extension. In order to read input from standard input, one (not both) might be
+specified as \`-'. In that case, the data is expected to be uncompressed.
 
-  The class limits are stored in a plain text file as sequence of bounds
-    L0
-    L1
-    L2
-    ...
-    LN
-  that results in following classes:
-    0:          x < L0
-    1:    L0 <= x < L1
-    2:    L1 <= x < L2
-    ...
-    N+1:  LN <= x
+Available flags for OPT:
+  -b, --bins=LIMITS
+    Select class LIMITS from BINS-file (default is \`${default_xdigit_bins}').
+
+  -f FIELD
+    Calculate class labels for FIELD (default is \`${default_xdigit_field}').
+
+  -t FS
+    $(fsep_help_message)
+
+  --with-class=CLASS
+    Write class labels into column CLASS (default is \`${default_xdigit_class}').
+    The new column is appended to the header.
+
+  --upper
+    Accept upper class limits.
+
+  -h, --help
+    $(help_help_message)
+
+Class limits
+For a given class, the label is assigned to all values that are between the
+lower and upper limits. By default this also includes the lower bound itself,
+i.e. lo <= x < hi. This behaviour can be changed by passing \`--upper'. In that
+case the upper bound is included, i.e. lo < x <= hi. Given the BINS file, the
+first row of BIN determines the lower limit for class 1(one). All values below
+this bound will be assigned to clas 0(zero). The last value of BIN determines
+the upper limit for class N (assuming, there are N+1 rows). All values above
+this bound will be assigned to class N+1.
+
+$(getopt_help_message "${program_name}" xawk XDIGIT_FLAGS "${default_xdigit_flags}")
+
+${program_name} uses a two-step approach to calculate class labels. In the
+first step a so-called \`meta-program' is generated from the BINS-file. This
+meta-program contains a set of awk-rules to match the specific classes. In step
+two, this meta-program is applied to the DATA-file to calculate the
+corresponding class labels. This is considered by accepting the environment
+variables \`XDIGIT_META_FLAGS' and \`XDIGIT_FLAGS' which influence the first
+and second step appropriately.
+
+Backend: $(which xawk)
 EOF
-      shift
-      exit 0
-      ;;
+    shift
+    exit 0
+    ;;
 
-    --)
-      shift
-      break
-      ;;
-      
+  --)
+    shift
+    break
+    ;;
+    
   esac
 done
 
 # Read input/bin files
-data=${1:?Missing data file}
-shift
+declare -r data_file=${1:?Missing DATA}
+declare -r bins_file=${2:?Missing BINS}
+shift 2
 
-bins=${1:?Missing data bins}
-shift
+declare -r user_field=${user_field:-${default_xdigit_field}}
+declare -r user_class=${user_class:-${default_xdigit_class}}
+declare -r user_bins=${user_bins:-${default_xdigit_bins}}
 
-# Create temporary file for awk-program
-awk_program=$(mktemp "${0##*/}".XXXXXX)
-awk_meta=$(mktemp "${0##*/}".XXXXXX)
+declare -r meta_program=$(mktemp)
+temporary_files+=("${meta_program}")
+generateDigitizeProgram "${user_field}" "${user_bins}" "${user_upper}" > "${meta_program}"
 
-class=${class_field:-$default_class}
-limit=${bin_field:-$default_bin}
-lower=${operator_lower:-"<="}
-upper=${operator_upper:-"<"}
+declare -r main_program=$(mktemp)
+temporary_files+=("${main_program}")
 
+# Check for double/invalid usage of `-'
+if [ "-" == "${data_file}" ] && [ "-" == "${bins_file}" ]; then
+  die -1 "Cannot read DATA and BINS from stdin!"
+fi
 
-cat > "$awk_meta" << EOF
-1 == NR {
-  cur_limit=\$_$limit;
-  min_limit=\$_$limit;
-  max_limit=\$_$limit;
-  cur_class=1;
-}
+# Apply meta-program to BINS
+xcat "${bins_file}" \
+  | xawk -t${fsep} -H --prefix=%% --suffix=%% "${meta_program}" $@ "${XDIGIT_META_FLAGS:-${default_xdigit_meta_flags}}" \
+  > "${main_program}"
 
-1 < NR {
-  print "("cur_limit" $lower %input%) && (%input% $upper "\$_$limit") { print "cur_class", \$0; next }";
-  min_limit = (min_limit > \$_$limit) ? \$_$limit : min_limit;
-  max_limit = (max_limit < \$_$limit) ? \$_$limit : max_limit;
-  cur_limit = \$_$limit;
-  cur_class += 1;
-}
+# Calculate class labels for DATA
+xcat "${data_file}" \
+  | xawk -t${fsep} --prefix=% --suffix=% "${main_program}" $@ "${XDIGIT_FLAGS:-${default_xdigit_flags}}" \
+  | xheader -t${fsep} --append="${user_class}"
 
-END {
-  print "(%input% $upper "min_limit") { print 0, \$0; next }";
-  print "("max_limit" $lower %input%) { print "cur_class", \$0; next }";
-}
-EOF
-
-xcat "$bins" \
-  | xawk -H -t "$fsep" -- -f "$awk_meta" \
-  | sed -e "s/%input%/\$_${input_field:-$default_input}/g" \
-  > "$awk_program"
-
-# Print data file either by name or from stdin. A new column is prepended to
-# contain the class label.
-cat "$data" \
-  | xawk -t "$fsep" -- -f "$awk_program" \
-  | xheader -t "$fsep" -p "$class"
-
-rm "$awk_program"
-rm "$awk_meta"
+# Report success to shell
+exit 0
diff --git a/xjoin b/xjoin
--- a/xjoin
+++ b/xjoin
@@ -1,113 +1,183 @@
-#!/bin/sh
+#!/bin/bash
+
+# Author:   Ronny Biemann
+#           Copyright 2016
+# File:     xjoin
+# License:  GPL-3.0
+
+function clean_up()
+{
+  #{{{
+  # Close file descriptors...
+  exec 5>&-
+  exec 4>&-
+
+  for file in "${temporary_files[@]}"; do rm -f "${file}" 2> /dev/null; done
+  rmdir "${tmpdir}" 2> /dev/null
+  true
+  #}}}
+}
+
+set -e
+trap clean_up 0 # EXIT-signal
 
 source xbase
+
+declare -r program_name=${0##*/}
+declare -r default_xjoin_flags=--check-order
+declare -r getopt_backend=$(find_program_like ${getopt_like_programs[@]})
+declare -r join_backend=$(find_program_like ${join_like_programs[@]})
+declare -a temporary_files
 
 # Initialize default field-separator
 fsep=$(set_fsep)
 
 # Parse command line arguments and feed parsed arguments
-args=$(getopt -o 1:2:dj:t: -l help,left-prefix:,left-suffix:,right-prefix:,right-suffix: -n "$program_name" -- "$@")
-eval set -- "$args"
+declare -r args=$(${getopt_backend} --options=1:2:dhj:t: \
+  --longoptions=help,left-prefix:,left-suffix:,right-prefix:,right-suffix: \
+  --name="${program_name}" -- "$@")
+eval set -- "${args}"
 
 # Parse arguments
 while true; do
-  case $1 in
-    -1)
-      left_field=${2:?Invalid left join field}
-      shift 2
-      ;;
+  case ${1} in
+  -1) # Set left key
+    left_field=${2}
+    shift 2
+    ;;
 
-    -2)
-      right_field=${2:?Invalud right join field}
-      shift 2
-      ;;
+  -2) # Set right key
+    right_field=${2}
+    shift 2
+    ;;
 
-    -d)
-      dry_run=1
-      shift
-      ;;
+  -d) # Enable dry-run mode
+    dry_run=1
+    shift
+    ;;
 
-    -j)
-      left_field=${2:?Invalid left join field}
-      right_field=${2:?Invalud right join field}
-      shift 2
-      ;;
+  -j) # Common join field
+    left_field=${2}
+    right_field=${2}
+    shift 2
+    ;;
 
-    --left-prefix)
-      left_prefix=$2
-      shift 2
-      ;;
+  -t) # Field separator
+    fsep=$(set_fsep ${2})
+    shift 2
+    ;;
 
-    --left-suffix)
-      left_suffix=$2
-      shift 2
-      ;;
+  --left-prefix)  # Prefix left columns
+    left_prefix=$2
+    shift 2
+    ;;
 
-    --right-prefix)
-      right_prefix=$2
-      shift 2
-      ;;
+  --left-suffix)  # Suffix left columns
+    left_suffix=$2
+    shift 2
+    ;;
 
-    --right-suffix)
-      right_suffix=$2
-      shift 2
-      ;;
+  --right-prefix) # Prefix right columns
+    right_prefix=$2
+    shift 2
+    ;;
 
-    --)
-      shift
-      break
-      ;;
+  --right-suffix) # Suffix right columns
+    right_suffix=$2
+    shift 2
+    ;;
+
+  -h|--help)  # Print help message
+    cat << EOF
+Usage: ${program_name} [OPT] LEFT RIGHT [-- ...]
+
+Join LEFT and RIGHT file on a common field. The join key is defined by column
+names. Therefore both LEFT and RIGHT file must contain a header.
+
+Available flags for OPT:
+  -1, -2, -j FIELD
+    Join LEFT, RIGHT or both files on FIELD
+
+  -d
+    Enable dry-run mode. The backend will not be invoked, but the configured
+    command will be written to standard output.
+
+  -t FS
+    $(fsep_help_message)
+
+  --left-prefix=STR, --left-suffix=STR
+  --right-prefix=STR, --right-suffix=STR
+    Add STD as prefix/suffix to LEFT/RIGHT column names
+
+  -h, --help
+    $(help_help_message)
+
+$(getopt_help_message "${program_name}" "${join_backend}" XJOIN_FLAGS "${default_xjoin_flags}")
+
+Backend: ${join_backend}
+EOF
+    shift
+    exit 0
+    ;;
+
+  --)
+    shift
+    break
+    ;;
   esac
 done
 
 # Non-option arguments are input files
-left_file=${1:?Invalid left input}
-shift
+declare -r left_file=${1:?Missing LEFT}
+declare -r right_file=${2:?Missing RIGHT}
+shift 2
 
-right_file=${1:?Invalid right input}
-shift
-
-# Check for double usage of `-'
-[ "-" = $left_file ] && [ "-" = $right_file ] && die -1 "Cannot read left and right data from stdin!"
-
-# # tmpdir=$(mktemp -d "$program_name"".XXXXXX")
-# tmpdir=$(mktemp -d "xjoin.XXXXXX")
-# tmp_left="$tmpdir/left"
-# tmp_right="$tmpdir/right"
-# 
-# touch "$tmp_left"
-# touch "$tmp_right"
-# 
-# #mkfifo "$tmp_left" "$tmp_right"
-# echo "-> $tmp_left -> $tmp_right"
-
-# Open left file
-if [ "-" = "$left_file" ]; then exec 4<&0
-else exec 4< "$left_file"
+# Check for double/invalid usage of `-'
+if [ "-" == "${left_file}" ] && [ "-" == "${right_file}" ]; then
+  die -1 "Cannot read LEFT and RIGHT from stdin!"
 fi
 
-# Open right file
-if [ "-" = "$right_file" ]; then exec 5<&0
-else exec 5< "$right_file"
-fi
+# Internally input files must be mapped to fifos. To keep them unique between
+# multiple instances, a random temporary directory is created as base for the
+# current instance.
+declare -r tmpdir=$(mktemp -d)
 
-# Read headers
+# Open left file as file descriptor(fd) 4:
+#
+# Use xcat to transparently decompress LEFT input into fifo. Afterwards this
+# fifo is connected to fd 4.
+declare -r left_in="${tmpdir}/left_in"
+mkfifo "${left_in}" || die -1 "Cannot create fifo \`${left_in}'!"
+temporary_files+=("${left_in}")
+xcat "${left_file}" > "${left_in}" &
+exec 4< "${left_in}"
+
+# Open right file as file descriptor(fd) 5: See above
+declare -r right_in="${tmpdir}/right_in"
+mkfifo "${right_in}" || die -1 "Cannot create fifo \`${right_in}'!"
+temporary_files+=("${right_in}")
+xcat "${right_file}" > "${right_in}" &
+exec 5< "${right_in}"
+
+# Read headers from LEFT and RIGHT input
 IFS= read -r left_raw_header <&4
 IFS= read -r right_raw_header <&5
 
-# Parse head line into x_fields and x_flags
-parse_header "$left_raw_header" "$fsep" x_left_
-parse_header "$right_raw_header" "$fsep" x_right_
+# Parse header
+# Column names are parsed into x_left_fields and x_right_fields
+parse_header "${left_raw_header}" "${fsep}" x_left_
+parse_header "${right_raw_header}" "${fsep}" x_right_
 
-# Find columns in x_fields and store indices into x_index and x_found
-find_fields x_left_fields[@] x_left_ $left_field
-find_fields x_right_fields[@] x_right_ $right_field
+# Locate left/right_field in corresponding header.
+# Results are stored in x_left/right_index and x_left/right_found
+locate_fields x_left_fields[@] x_left_ "${left_field}"
+locate_fields x_right_fields[@] x_right_ "${right_field}"
 
 # Apply prefix/suffix for left/right
-[ ! -z "$left_prefix" ] && add_prefix_to_fields x_left_fields[@] "$left_prefix" x_left_
-[ ! -z "$left_suffix" ] && add_suffix_to_fields x_left_fields[@] "$left_suffix" x_left_
-[ ! -z "$right_prefix" ] && add_prefix_to_fields x_right_fields[@] "$right_prefix" x_right_
-[ ! -z "$right_suffix" ] && add_suffix_to_fields x_right_fields[@] "$right_suffix" x_right_
+[ -n "${left_prefix}" ] && add_prefix_to_fields x_left_fields[@] "${left_prefix}" x_left_
+[ -n "${left_suffix}" ] && add_suffix_to_fields x_left_fields[@] "${left_suffix}" x_left_
+[ -n "${right_prefix}" ] && add_prefix_to_fields x_right_fields[@] "${right_prefix}" x_right_
+[ -n "${right_suffix}" ] && add_suffix_to_fields x_right_fields[@] "${right_suffix}" x_right_
 
 # Build output header
 # 1. Delete left/right join fields
@@ -117,36 +187,44 @@ if [ 0 -eq ${dry_run:-0} ]; then
   delete_fields_by_index x_left_fields[@] x_left_index[@] x_left_
   delete_fields_by_index x_right_fields[@] x_right_index[@] x_right_
 
-  tmp_left_header=$(join_by x_left_fields[@] "$fsep")
-  tmp_right_header=$(join_by x_right_fields[@] "$fsep")
-  echo "$join_field""$fsep""$tmp_left_header""$fsep""$tmp_right_header"
+  tmp_left_header=$(join_by x_left_fields[@] "${fsep}")
+  tmp_right_header=$(join_by x_right_fields[@] "${fsep}")
+  echo "${join_field}${fsep}${tmp_left_header}${fsep}${tmp_right_header}"
 fi
 
 # Create temporary files for join-program
-tmpdir=$(mktemp -d xjoin_XXXXXX)
-tmp_left="$tmpdir/left"
-tmp_right="$tmpdir/right"
+declare -r left_fifo="${tmpdir}/left"
+declare -r right_fifo="${tmpdir}/right"
 
-mkfifo "$tmp_left"
-mkfifo "$tmp_right"
+mkfifo "${left_fifo}" || die -1 "Cannot create fifo \`${left_fifo}'!"
+temporary_files+=("${left_fifo}")
+
+mkfifo "${right_fifo}" || die -1 "Cannot create fifo \`${right_fifo}'!"
+temporary_files+=("${right_fifo}")
 
 # Connect file descriptors to fifos
-cat <&4 > "$tmp_left" &
-cat <&5 > "$tmp_right" &
+cat <&4 > "${left_fifo}" &
+cat <&5 > "${right_fifo}" &
 
-cmd=$(replace_fsep "$_join" "$fsep")
-cmd+=" --check-order"
-cmd+=" -1$((${x_left_index[0]} + 1))"
-cmd+=" -2$((${x_right_index[0]} + 1))"
+# Configure field-separator in join program
+cmd="${join_backend} -t${fsep}"
 
-# Prepend echo-command for dry-run-mode
-[ 0 -ne ${dry_run:-0} ] && cmd="$_echo ""$cmd"
+# Get column-index for left/right join field
+declare -ri left_no=$((${x_left_index[0]} + 1))
+declare -ri right_no=$((${x_right_index[0]} + 1))
+cmd+=" -1${left_no} -2${right_no}"
 
-# Run join-command and pass options after `--' to join
-$cmd "$tmp_left" "$tmp_right" "$@"
+# Pass input data via fifos
+cmd+=" '${left_fifo}' '${right_fifo}'"
 
-# Close file descriptors and delete temporary fifos
-exec 5>&-
-exec 4>&-
-rm "$tmp_left" "$tmp_right"
-rmdir "$tmpdir"
+# Add non-option arguments and other options
+cmd+=" $@ ${XJOIN_FLAGS:-${default_xjoin_flags}}"
+declare -r cmd
+
+# If dry-run mode is enabled, cmd will only be echoed
+if [ 0 -eq ${dry_run:-0} ]; then eval ${cmd}
+else echo "${cmd}"
+fi
+
+# Report success to shell
+exit 0
